plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion rootProject.ext.android.compileSdkVersion
    buildToolsVersion rootProject.ext.android.buildToolsVersion
    namespace = "com.yiman.ad.adbid"
    defaultConfig {
        applicationId "com.adbid.sdk.demo"
        minSdkVersion rootProject.ext.android.minSdkVersion
        targetSdkVersion rootProject.ext.android.targetSdkVersion
        versionCode 20100019
        versionName "2.1.0.19"
    }
    signingConfigs {
        debug {
            storeFile file("./test.jks") // 密钥库文件路径
            storePassword "123456" // 密钥库密码
            keyAlias "key0" // 密钥别名
            keyPassword "123456" // 密钥密码
            enableV2Signing true
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            // 是否混淆
            minifyEnabled false
            // 混淆配置文件的位置
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            shrinkResources true
            // 混淆配置文件的位置
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    //demo依赖库
    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)
    implementation(libs.glide)
    implementation(libs.androidx.recyclerview)
    implementation(libs.androidx.viewpager2)
    implementation(libs.androidx.constraintlayout)
    implementation 'com.geyifeng.immersionbar:immersionbar:3.2.2'






    //*********************广告聚合接入*******************************************

    //领摩聚合核心库(默认接入领摩ADX)
    implementation(files("libs/adbid_sdk_2.1.0.20_0715_1215.aar"))



    //萤石
    implementation(files("libs/adbid_ezviz_1.0.0_0511_1050.aar"))
    implementation(files("libs/ezviz-sdk-4.2.0.0721.aar"))
    implementation "com.google.code.gson:gson:2.8.9"
    implementation 'io.reactivex.rxjava2:rxjava:2.2.19'
    implementation "com.squareup.okhttp3:okhttp:4.9.0"
    implementation "com.squareup.retrofit2:retrofit:2.8.1"
    implementation "com.github.bumptech.glide:glide:4.11.0"
    implementation "com.airbnb.android:lottie:3.7.2"
}







